var lookups = [
{"id":"3","unit":"Celsius","plural_unit":"Celsius","symbols":"ºC","measures":"temperature","region":"INTERNATIONAL","converter":{"convert_to":"Celsius","conversion_factor":"1.0000000","conversion_factor_exponent":"0","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"4","unit":"Fahrenheit","plural_unit":"Fahrenheit","symbols":"ºF","measures":"temperature","region":"INTERNATIONAL","converter":{"convert_to":"Fahrenheit","conversion_factor":"1.8500000","conversion_factor_exponent":"0","conversion_factor_offset":"32.00"},"converts_to":null,"class":null,"metric":null},
{"id":"5","unit":"Kelvin","plural_unit":"Kelvin","symbols":"K","measures":"temperature","region":"INTERNATIONAL","converter":{"convert_to":"Kelvin","conversion_factor":"1.0000000","conversion_factor_exponent":"0","conversion_factor_offset":"273.15"},"converts_to":null,"class":null,"metric":null},
{"id":"6","unit":"Rankine","plural_unit":"Rankine","symbols":"ºR","measures":"temperature","region":"INTERNATIONAL","converter":{"convert_to":"Rankine","conversion_factor":"1.8000000","conversion_factor_exponent":"0","conversion_factor_offset":"491.67"},"converts_to":null,"class":null,"metric":null},
{"id":"7","unit":"Parsec","plural_unit":"Parsecs","symbols":"pc","measures":"length","region":"INTERNATIONAL","converter":{"convert_to":"Parsecs","conversion_factor":"3.2407793","conversion_factor_exponent":"-17","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"8","unit":"Lightyear","plural_unit":"Lightyears","symbols":"ly","measures":"length","region":"INTERNATIONAL","converter":{"convert_to":"Lightyears","conversion_factor":"1.0570008","conversion_factor_exponent":"-16","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"9","unit":"Kilometer","plural_unit":"Kilometers","symbols":"km","measures":"length","region":"INTERNATIONAL","converter":{"convert_to":"Kilometers","conversion_factor":"1.0000000","conversion_factor_exponent":"-3","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"10","unit":"Meter","plural_unit":"Meters","symbols":"m","measures":"length","region":"INTERNATIONAL","converter":{"convert_to":"Meters","conversion_factor":"1.0000000","conversion_factor_exponent":"0","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"11","unit":"Decimeter","plural_unit":"Decimeters","symbols":"dm","measures":"length","region":"INTERNATIONAL","converter":{"convert_to":"Decimeters","conversion_factor":"1.0000000","conversion_factor_exponent":"1","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"12","unit":"Centimeter","plural_unit":"Centimeters","symbols":"cm","measures":"length","region":"INTERNATIONAL","converter":{"convert_to":"Centimeters","conversion_factor":"1.0000000","conversion_factor_exponent":"2","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"13","unit":"Millimeter","plural_unit":"Millimeters","symbols":"mm","measures":"length","region":"INTERNATIONAL","converter":{"convert_to":"Millimeters","conversion_factor":"1.0000000","conversion_factor_exponent":"3","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"14","unit":"Nautical Mile","plural_unit":"Nautical Miles","symbols":"UK nmi","measures":"length","region":"UK","converter":{"convert_to":"Nautical Miles","conversion_factor":"5.3961182","conversion_factor_exponent":"-4","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"15","unit":"Mile","plural_unit":"Miles","symbols":"mi","measures":"length","region":"INTERNATIONAL","converter":{"convert_to":"Miles","conversion_factor":"6.2137119","conversion_factor_exponent":"-4","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"16","unit":"Nautical Mile","plural_unit":"Nautical Miles","symbols":"US nmi","measures":"length","region":"US","converter":{"convert_to":"Nautical Miles","conversion_factor":"5.3995680","conversion_factor_exponent":"-4","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"17","unit":"Nautical Mile","plural_unit":"Nautical Miles","symbols":"nmi","measures":"length","region":"INTERNATIONAL","converter":{"convert_to":"Nautical Miles","conversion_factor":"5.3995680","conversion_factor_exponent":"-4","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"18","unit":"Furlong","plural_unit":"Furlongs","symbols":"fur","measures":"length","region":"INTERNATIONAL","converter":{"convert_to":"Furlongs","conversion_factor":"4.9709596","conversion_factor_exponent":"-3","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"19","unit":"Chain","plural_unit":"Chains","symbols":"ch","measures":"length","region":"INTERNATIONAL","converter":{"convert_to":"Chains","conversion_factor":"4.9709596","conversion_factor_exponent":"-2","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"20","unit":"Yard","plural_unit":"Yards","symbols":"yd","measures":"length","region":"INTERNATIONAL","converter":{"convert_to":"Yards","conversion_factor":"1.0936133","conversion_factor_exponent":"0","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"21","unit":"Feet","plural_unit":"Feet","symbols":"ft","measures":"length","region":"INTERNATIONAL","converter":{"convert_to":"Feet","conversion_factor":"3.2808399","conversion_factor_exponent":"0","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"22","unit":"Inch","plural_unit":"Inches","symbols":"in","measures":"length","region":"INTERNATIONAL","converter":{"convert_to":"Inches","conversion_factor":"3.9370079","conversion_factor_exponent":"1","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"23","unit":"League","plural_unit":"Leagues","symbols":"US lea","measures":"length","region":"US","converter":{"convert_to":"US Leagues","conversion_factor":"2.0712332","conversion_factor_exponent":"-4","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"24","unit":"Nautical League","plural_unit":"Nautical Leagues","symbols":"nl","measures":"length","region":"INTERNATIONAL","converter":{"convert_to":"Nautical Leagues","conversion_factor":"1.7998560","conversion_factor_exponent":"-4","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"25","unit":"League","plural_unit":"Leagues","symbols":"UK lg","measures":"length","region":"UK","converter":{"convert_to":"Leagues","conversion_factor":"2.0700000","conversion_factor_exponent":"-4","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"26","unit":"Nautical League","plural_unit":"Nautical Leagues","symbols":"UK nl","measures":"length","region":"UK","converter":{"convert_to":"UK Nautical Leagues","conversion_factor":"1.7987061","conversion_factor_exponent":"-4","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"27","unit":"Microinch","plural_unit":"Microinches","symbols":"µin","measures":"length","region":"INTERNATIONAL","converter":{"convert_to":"Microinches","conversion_factor":"3.9370079","conversion_factor_exponent":"7","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"28","unit":"Micrometer","plural_unit":"Micrometer","symbols":"µm","measures":"length","region":"INTERNATIONAL","converter":{"convert_to":"Micrometer","conversion_factor":"1.0000000","conversion_factor_exponent":"6","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"29","unit":"Micron","plural_unit":"Microns","symbols":"µ","measures":"length","region":"INTERNATIONAL","converter":{"convert_to":"Microns","conversion_factor":"1.0000000","conversion_factor_exponent":"6","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"38","unit":"Square Kilometer","plural_unit":"Square Kilometers","symbols":"km²","measures":"area","region":"INTERNATIONAL","converter":{"convert_to":"Square Kilometers","conversion_factor":"1.0000000","conversion_factor_exponent":"-6","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"39","unit":"Hectare","plural_unit":"Hectares","symbols":"ha","measures":"area","region":"INTERNATIONAL","converter":{"convert_to":"Hectares","conversion_factor":"1.0000000","conversion_factor_exponent":"-4","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"42","unit":"Square Meter","plural_unit":"Square Meters","symbols":"m²","measures":"area","region":"INTERNATIONAL","converter":{"convert_to":"Square Meters","conversion_factor":"1.0000000","conversion_factor_exponent":"0","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"43","unit":"Square Centimeter","plural_unit":"Square Centimeters","symbols":"cm²","measures":"area","region":"INTERNATIONAL","converter":{"convert_to":"Square Centimeters","conversion_factor":"1.0000000","conversion_factor_exponent":"4","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"44","unit":"Square Millimeter","plural_unit":"Square Millimeters","symbols":"mm²","measures":"area","region":"INTERNATIONAL","converter":{"convert_to":"Square Millimeters","conversion_factor":"1.0000000","conversion_factor_exponent":"6","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"45","unit":"Square Micrometer","plural_unit":"Square Micrometers","symbols":"sq µm","measures":"area","region":"INTERNATIONAL","converter":{"convert_to":"Square Micrometers","conversion_factor":"1.0000000","conversion_factor_exponent":"12","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"46","unit":"Square Micron","plural_unit":"Square Microns","symbols":"µ²","measures":"area","region":"INTERNATIONAL","converter":{"convert_to":"Square Microns","conversion_factor":"1.0000000","conversion_factor_exponent":"12","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"47","unit":"Square Mile","plural_unit":"Square Miles","symbols":"mi²","measures":"area","region":"INTERNATIONAL","converter":{"convert_to":"Square Miles","conversion_factor":"3.8610216","conversion_factor_exponent":"-7","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"48","unit":"Acre","plural_unit":"Acres","symbols":"ac","measures":"area","region":"INTERNATIONAL","converter":{"convert_to":"Acres","conversion_factor":"2.4710538","conversion_factor_exponent":"-4","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"49","unit":"Square Yard","plural_unit":"Square Yards","symbols":"yd²","measures":"area","region":"INTERNATIONAL","converter":{"convert_to":"Square Yards","conversion_factor":"1.1959900","conversion_factor_exponent":"0","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"50","unit":"Square Feet","plural_unit":"Square Feet","symbols":"ft²","measures":"area","region":"INTERNATIONAL","converter":{"convert_to":"Square Feet","conversion_factor":"1.0763910","conversion_factor_exponent":"1","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"51","unit":"Square Inches","plural_unit":"Square Inches","symbols":"in²","measures":"area","region":"INTERNATIONAL","converter":{"convert_to":"Square Inches","conversion_factor":"1.5500031","conversion_factor_exponent":"3","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"52","unit":"Square Microinch","plural_unit":"Square Microinches","symbols":"µin²","measures":"area","region":"INTERNATIONAL","converter":{"convert_to":"Square Microinches","conversion_factor":"1.5500310","conversion_factor_exponent":"15","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"53","unit":"Cubic Meter","plural_unit":"Cubic Meters","symbols":"m³","measures":"volume","region":"INTERNATIONAL","converter":{"convert_to":"Cubic Meters","conversion_factor":"1.0000000","conversion_factor_exponent":"-3","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"54","unit":"Liter","plural_unit":"Liters","symbols":"L","measures":"volume","region":"INTERNATIONAL","converter":{"convert_to":"Liters","conversion_factor":"1.0000000","conversion_factor_exponent":"0","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"55","unit":"Centiliter","plural_unit":"Centiliters","symbols":"cl","measures":"volume","region":"INTERNATIONAL","converter":{"convert_to":"Centiliters","conversion_factor":"1.0000000","conversion_factor_exponent":"2","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"56","unit":"Milliliter","plural_unit":"Milliliters","symbols":"mL","measures":"volume","region":"INTERNATIONAL","converter":{"convert_to":"Milliliters","conversion_factor":"1.0000000","conversion_factor_exponent":"3","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"57","unit":"Cubic Yard","plural_unit":"Cubic Yards","symbols":"yd³","measures":"volume","region":"INTERNATIONAL","converter":{"convert_to":"Cubic Yards","conversion_factor":"1.3079506","conversion_factor_exponent":"-3","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"58","unit":"Barrel (Dry)","plural_unit":"US Barrels (Dry)","symbols":"US bbl dry","measures":"volume","region":"US","converter":{"convert_to":"US Barrels (Dry)","conversion_factor":"8.6484916","conversion_factor_exponent":"-3","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"59","unit":"Barrel (Liquid)","plural_unit":"Barrels (Liquid)","symbols":"US bbl lqd","measures":"volume","region":"US","converter":{"convert_to":"US Barrels (Liquid)","conversion_factor":"8.3864144","conversion_factor_exponent":"-3","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"60","unit":"Barrel (Oil)","plural_unit":"Barrels (Oil)","symbols":"US bbl oil","measures":"volume","region":"US","converter":{"convert_to":"US Barrels (Oil)","conversion_factor":"6.2898108","conversion_factor_exponent":"-3","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"61","unit":"Barrel (Federal)","plural_unit":"Barrels (Federal)","symbols":"US bbl fed","measures":"volume","region":"US","converter":{"convert_to":"US Barrels (Federal)","conversion_factor":"8.5216791","conversion_factor_exponent":"-3","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"62","unit":"Barrel","plural_unit":"Barrels","symbols":"UK bbl","measures":"volume","region":"UK","converter":{"convert_to":"UK Barrels","conversion_factor":"6.1102569","conversion_factor_exponent":"-3","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"63","unit":"Gallon (Liquid)","plural_unit":"Gallons (Liquid)","symbols":"US gal lqd","measures":"volume","region":"US","converter":{"convert_to":"US Gallons (Liquid)","conversion_factor":"2.6417205","conversion_factor_exponent":"-1","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"64","unit":"Gallon (Dry)","plural_unit":"Gallons (Dry)","symbols":"US gal dry","measures":"volume","region":"US","converter":{"convert_to":"US Gallons (Dry)","conversion_factor":"2.2702074","conversion_factor_exponent":"-1","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"65","unit":"Gallon","plural_unit":"Gallons","symbols":"UK gal","measures":"volume","region":"UK","converter":{"convert_to":"UK Gallons","conversion_factor":"2.1996925","conversion_factor_exponent":"-1","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"66","unit":"Cubic Feet","plural_unit":"Cubic Feet","symbols":"ft³","measures":"volume","region":"INTERNATIONAL","converter":{"convert_to":"Cubic Feet","conversion_factor":"3.5314667","conversion_factor_exponent":"-2","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"70","unit":"Pint (Liquid)","plural_unit":"Pints (Liquid)","symbols":"US pt lqd","measures":"volume","region":"US","converter":{"convert_to":"US Pints (Liquid)","conversion_factor":"2.1133764","conversion_factor_exponent":"0","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"71","unit":"Pint (Dry)","plural_unit":"Pints (Dry)","symbols":"US pt dry","measures":"volume","region":"US","converter":{"convert_to":"US Pints (Dry)","conversion_factor":"1.8161659","conversion_factor_exponent":"0","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"72","unit":"Pint","plural_unit":"Pints","symbols":"pt","measures":"volume","region":"UK","converter":{"convert_to":"UK Pints","conversion_factor":"1.7597540","conversion_factor_exponent":"0","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"73","unit":"Cup","plural_unit":"Cups","symbols":"cup US","measures":"volume","region":"US","converter":{"convert_to":"US Cups","conversion_factor":"4.2267528","conversion_factor_exponent":"0","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"74","unit":"Cup","plural_unit":"Cups","symbols":"cup can","measures":"volume","region":"CANADA","converter":{"convert_to":"Canadian Cups","conversion_factor":"4.3993850","conversion_factor_exponent":"0","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"75","unit":"Cup","plural_unit":"Cups","symbols":"cup metric","measures":"volume","region":"INTERNATIONAL","converter":{"convert_to":"Metric Cups","conversion_factor":"4.0000000","conversion_factor_exponent":"0","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"76","unit":"Gill","plural_unit":"Gills","symbols":"US gi","measures":"volume","region":"US","converter":{"convert_to":"US Gills","conversion_factor":"8.4535057","conversion_factor_exponent":"0","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"77","unit":"Tablespoon","plural_unit":"Tablespoons","symbols":"US tblsp","measures":"volume","region":"US","region":"INTERNATIONAL","converter":{"convert_to":"US Tablespoons","conversion_factor":"6.7628045","conversion_factor_exponent":"1","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"78","unit":"Tablespoon","plural_unit":"Tablespoons","symbols":"UK tblsp","measures":"volume","region":"UK","converter":{"convert_to":"UK Tablespoons","conversion_factor":"7.0390100","conversion_factor_exponent":"1","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"79","unit":"Tablespoon","plural_unit":"Tablespoons","symbols":"metric tblsp","measures":"volume","region":"INTERNATIONAL","converter":{"convert_to":"Metric Tablespoons","conversion_factor":"6.6666666","conversion_factor_exponent":"1","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"80","unit":"Teaspoon","plural_unit":"Teaspoons","symbols":"US tsp","measures":"volume","region":"US","converter":{"convert_to":"US Teaspoons","conversion_factor":"2.0288414","conversion_factor_exponent":"2","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"81","unit":"Teaspoon","plural_unit":"Teaspoons","symbols":"UK tsp","measures":"volume","region":"UK","converter":{"convert_to":"UK Teaspoons","conversion_factor":"2.8156000","conversion_factor_exponent":"2","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"82","unit":"Teaspoon","plural_unit":"Teaspoons","symbols":"metric tsp","measures":"volume","region":"INTERNATIONAL","converter":{"convert_to":"Metric Teaspoons","conversion_factor":"2.0000000","conversion_factor_exponent":"2","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"83","unit":"Fluid Ounce","plural_unit":"Fluid Ounces","symbols":"us fl oz","measures":"volume","region":"US","converter":{"convert_to":"US Fluid Ounces","conversion_factor":"3.3814023","conversion_factor_exponent":"1","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"84","unit":"Fluid Ounce","plural_unit":"Fluid Ounces","symbols":"uk fl oz","measures":"volume","region":"UK","converter":{"convert_to":"UK Fluid Ounces","conversion_factor":"3.5195080","conversion_factor_exponent":"1","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"85","unit":"Cubic Inches","plural_unit":"Cubic Inches","symbols":"in³","measures":"volume","region":"INTERNATIONAL","converter":{"convert_to":"Cubic Inches","conversion_factor":"6.1023744","conversion_factor_exponent":"1","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"86","unit":"Cubic Centimeter","plural_unit":"Cubic Centimeters","symbols":"cm³","measures":"volume","region":"INTERNATIONAL","converter":{"convert_to":"Cubic Centimeters","conversion_factor":"1.0000000","conversion_factor_exponent":"3","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"87","unit":"Cubic Millimeter","plural_unit":"Cubic Millimeters","symbols":"mm³","measures":"volume","region":"INTERNATIONAL","converter":{"convert_to":"Cubic Millimeters","conversion_factor":"1.0000000","conversion_factor_exponent":"6","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"88","unit":"Microliter","plural_unit":"Microliter","symbols":"µl","measures":"volume","region":"INTERNATIONAL","converter":{"convert_to":"Microliter","conversion_factor":"1.0000000","conversion_factor_exponent":"6","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"90","unit":"Gill","plural_unit":"Gills","symbols":"UK gill","measures":"volume","region":"UK","converter":{"convert_to":"Gills (UK)","conversion_factor":"7.0390159","conversion_factor_exponent":"0","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"91","unit":"Ton","plural_unit":"Tons","symbols":"t","measures":"weight","region":"INTERNATIONAL","converter":{"convert_to":"Metric Tons (or Tonnes)","conversion_factor":"1.0000000","conversion_factor_exponent":"-3","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"92","unit":"Kilogram","plural_unit":"Kilograms","symbols":"kg","measures":"weight","region":"INTERNATIONAL","converter":{"convert_to":"Kilograms","conversion_factor":"1.0000000","conversion_factor_exponent":"0","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"93","unit":"Gram","plural_unit":"Grams","symbols":"g","measures":"weight","region":"INTERNATIONAL","converter":{"convert_to":"Grams","conversion_factor":"1.0000000","conversion_factor_exponent":"3","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"94","unit":"Carat","plural_unit":"Carats","symbols":"ct","measures":"weight","region":"INTERNATIONAL","converter":{"convert_to":"Carats","conversion_factor":"5.0000000","conversion_factor_exponent":"3","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"95","unit":"Milligram","plural_unit":"Milligrams","symbols":"mg","measures":"weight","region":"INTERNATIONAL","converter":{"convert_to":"Milligrams","conversion_factor":"1.0000000","conversion_factor_exponent":"6","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"96","unit":"Microgram","plural_unit":"Micrograms","symbols":"µg","measures":"weight","region":"INTERNATIONAL","converter":{"convert_to":"Micrograms","conversion_factor":"1.0000000","conversion_factor_exponent":"9","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"97","unit":"Long Ton","plural_unit":"Long Tons","symbols":"UK t","measures":"weight","region":"UK","converter":{"convert_to":"Long Tons (UK)","conversion_factor":"9.8420653","conversion_factor_exponent":"-4","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"98","unit":"Short Ton","plural_unit":"Short Tons","symbols":"US t","measures":"weight","region":"US","converter":{"convert_to":"Short Tons (US)","conversion_factor":"1.1023113","conversion_factor_exponent":"-3","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"99","unit":"Short Hundredweight","plural_unit":"Short Hundredweights","symbols":"sh cwt","measures":"weight","region":"US","converter":{"convert_to":"Short Hundredweights (US)","conversion_factor":"2.2046226","conversion_factor_exponent":"-2","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"100","unit":"Long Hundredweight","plural_unit":"Long Hundredweights","symbols":"cwt long","measures":"weight","region":"UK","converter":{"convert_to":"Long Hundredweights (UK)","conversion_factor":"1.9684131","conversion_factor_exponent":"-2","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"101","unit":"Stone","plural_unit":"Stones","symbols":"st","measures":"weight","region":"INTERNATIONAL","converter":{"convert_to":"Stones","conversion_factor":"1.5747304","conversion_factor_exponent":"-1","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"102","unit":"Pound","plural_unit":"Pounds","symbols":"lb","measures":"weight","region":"INTERNATIONAL","converter":{"convert_to":"Pounds","conversion_factor":"2.2046228","conversion_factor_exponent":"0","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"103","unit":"Troy Pound","plural_unit":"Troy Pounds","symbols":"t lb","measures":"weight","region":"INTERNATIONAL","converter":{"convert_to":"Troy Pounds","conversion_factor":"2.6792289","conversion_factor_exponent":"0","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"104","unit":"Troy Ounce","plural_unit":"Troy Ounces","symbols":"t oz","measures":"weight","region":"INTERNATIONAL","converter":{"convert_to":"Troy Ounces","conversion_factor":"3.2150747","conversion_factor_exponent":"1","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"105","unit":"Ounce","plural_unit":"Ounces","symbols":"oz","measures":"weight","region":"INTERNATIONAL","converter":{"convert_to":"Ounces","conversion_factor":"3.5273962","conversion_factor_exponent":"1","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"106","unit":"Pennyweight","plural_unit":"Pennyweights","symbols":"dwt","measures":"weight","region":"INTERNATIONAL","converter":{"convert_to":"Pennyweights","conversion_factor":"6.4301493","conversion_factor_exponent":"2","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"107","unit":"Grain","plural_unit":"Grains","symbols":"gr","measures":"weight","region":"INTERNATIONAL","converter":{"convert_to":"Grains","conversion_factor":"1.5432358","conversion_factor_exponent":"4","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"108","unit":"Quart (Dry)","plural_unit":"Quarts (Dry)","symbols":"US qt dry","measures":"volume","region":"US","converter":{"convert_to":"US Quarts (Dry)","conversion_factor":"9.0808302","conversion_factor_exponent":"-1","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"109","unit":"Quart (Liquid)","plural_unit":"Quarts (Liquid)","symbols":"qt","measures":"volume","region":"US","converter":{"convert_to":"US Quarts (Liquid)","conversion_factor":"1.0566882","conversion_factor_exponent":"0","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"110","unit":"Quart","plural_unit":"Quarts","symbols":"UK qt","measures":"volume","region":"UK","converter":{"convert_to":"UK Quarts","conversion_factor":"8.7987699","conversion_factor_exponent":"-1","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"111","unit":"Kiloliter","plural_unit":"Kiloliters","symbols":"kl","measures":"volume","region":"INTERNATIONAL","converter":{"convert_to":"Kiloliters","conversion_factor":"1.0000000","conversion_factor_exponent":"-3","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"112","unit":"Tonne","plural_unit":"Tonnes","symbols":"T","measures":"weight","region":"INTERNATIONAL","converter":{"convert_to":"Tonnes","conversion_factor":"1.0000000","conversion_factor_exponent":"-3","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"113","unit":"League","plural_unit":"Leagues","symbols":"Lea","measures":"length","region":"INTERNATIONAL","converter":{"convert_to":"Leagues","conversion_factor":"1.0000000","conversion_factor_exponent":"0","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"114","unit":"Nautical Mile","plural_unit":"Nautical Miles","symbols":"N mi","measures":"length","region":"INTERNATIONAL","converter":{"convert_to":"Nautical Miles","conversion_factor":"1.0000000","conversion_factor_exponent":"0","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"115","unit":"Second","plural_unit":"Seconds","symbols":"s","measures":"time","region":"INTERNATIONAL","converter":{"convert_to":"Seconds","conversion_factor":"1.0000000","conversion_factor_exponent":"0","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"118","unit":"Minute","plural_unit":"Minutes","symbols":"min","measures":"time","region":"INTERNATIONAL","converter":{"convert_to":"Minutes","conversion_factor":"1.6666667","conversion_factor_exponent":"-2","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"119","unit":"Hour","plural_unit":"Hour","symbols":"hr","measures":"time","region":"INTERNATIONAL","converter":{"convert_to":"Hour","conversion_factor":"2.7777778","conversion_factor_exponent":"-4","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"120","unit":"Day","plural_unit":"Day","symbols":"day","measures":"time","region":"INTERNATIONAL","converter":{"convert_to":"Day","conversion_factor":"1.1574074","conversion_factor_exponent":"-5","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"122","unit":"Newton","plural_unit":"Newton","symbols":"ºN","measures":"temperature","region":"INTERNATIONAL","converter":{"convert_to":"Newton","conversion_factor":"3.3000000","conversion_factor_exponent":"-1","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"123","unit":"Réaumur","plural_unit":"Réaumur","symbols":"ºRé","measures":"temperature","region":"INTERNATIONAL","converter":{"convert_to":"Réaumur","conversion_factor":"8.0000000","conversion_factor_exponent":"-1","conversion_factor_offset":"0.00"},"converts_to":null,"class":null,"metric":null},
{"id":"124","unit":"Rømer","plural_unit":"Rømer","symbols":"°Rø","measures":"temperature","region":"INTERNATIONAL","converter":{"convert_to":"Rømer","conversion_factor":"5.2500000","conversion_factor_exponent":"-1","conversion_factor_offset":"7.50"},"converts_to":null,"class":null,"metric":null},
{"id":"125","unit":"Delisle","plural_unit":"Delisle","symbols":"°De","measures":"temperature","region":"INTERNATIONAL","converter":{"convert_to":"Delisle","conversion_factor":"1.5000000","conversion_factor_exponent":"0","conversion_factor_offset":"-100.00"},"converts_to":null,"class":null,"metric":null}
];

// alert("Lookups: "+lookups.length);

var body = $("body").html();

var findMatch = function(match, group1, group2, index, original) {
  var valueToBeConverted = "Equivalent to: "+ match.replace(/\D/g,'') + "\n "+ unit;

  return "<span title='"+valueToBeConverted+"' style='text-transform:uppercase;'>"+match+"</span>";
};

for (var i=0; i < lookups.length; i++) {
  var unit = lookups[i].unit;
  // var searchTerm = new RegExp("\\b[0-9]+[0-9,-\\s]*\\s?"+unit+"[s]?\\b", "gi");
  var searchTerm = new RegExp("\\b[1-9](?:\\d{0,2})(?:,\\d{3})*(?:\\.\\d*[1-9])?\\s?"+unit+"\\b|0?\\.\\d*[1-9]\\s?"+unit+"\\b|0\\s?"+unit+"\\b", "gi");
  // \b[1-9](?:\d{0,2})(?:,\d{3})*(?:\.\d*[1-9])?\s?km|0?\.\d*[1-9]\s?km|0\s?km\b


  // Replace values with name
  var replaced = body.replace(searchTerm, findMatch);
  body = replaced;

  // Replace values with symbols
  replaced = '';
  unit = lookups[i].symbols;
  var searchTerm = new RegExp("\\b[1-9](?:\\d{0,2})(?:,\\d{3})*(?:\\.\\d*[1-9])?\\s?"+unit+"\\b|0?\\.\\d*[1-9]\\s?"+unit+"\\b|0\\s?"+unit+"\\b", "gi");

  replaced = body.replace(searchTerm, findMatch);
  body = replaced;
  
  // Replace values with plural units
  replaced = '';
  unit = lookups[i].plural_unit;
  var searchTerm = new RegExp("\\b[1-9](?:\\d{0,2})(?:,\\d{3})*(?:\\.\\d*[1-9])?\\s?"+unit+"\\b|0?\\.\\d*[1-9]\\s?"+unit+"\\b|0\\s?"+unit+"\\b", "gi");

  replaced = body.replace(searchTerm, findMatch);
  body = replaced;
}



$("body").html(body);
